version: '3.8'
services:
  investment:
    build: .
    command: >-
      uvicorn api.investment.main:app --host 0.0.0.0
      --port ${INVESTMENT_API_PORT:-8000}
    env_file: .env
    ports:
      - "${INVESTMENT_API_PORT:-8000}:${INVESTMENT_API_PORT:-8000}"
  inventory:
    build: .
    command: >-
      uvicorn api.inventory.main:app --host 0.0.0.0
      --port ${INVENTORY_API_PORT:-8001}
    env_file: .env
    ports:
      - "${INVENTORY_API_PORT:-8001}:${INVENTORY_API_PORT:-8001}"
